### ISSUE TITLE
Publish ES5 code to npm

### ISSUE THREAD

**Issue by chrisinajar** [sindresorhus/class-names#1]
I am aware that you as an individual don't usually do this since node is your primary target, however this is clearly a library for use in browsers, clearly for react, but yet cannot be used with `create-react-app`.

Here's the relevant part of their documentation: http://bit.ly/2tRViJ9

I'm happy to do the work and open a PR, I just want to make sure there's not an ideological reason blocking this functionality.

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in adding a compile-step just because of `create-react-app` limitations. CRA v2 will compile dependencies, so when it's out, everything will be good again.

**Comment by sindresorhus** [comment]
In the meantime, you can use this module through https://github.com/sindresorhus/react-extras, which *is* transpiled.
