### ISSUE TITLE
Noticable differences between two classnames packages

### ISSUE THREAD

**Issue by dextermb** [sindresorhus/class-names#2]
Hey there,

I've been following some of your packages for a good while. I've been using [`JedWatson/classnames` ](https://github.com/JedWatson/classnames) as my `classnames` library. 

It's interesting to see the differences between the two- for example Jed's allows an `array`.

Did you base yours off Jeb's? If not perhaps you might find it interesting to look at his source.

**Comment by sindresorhus** [comment]
It's already addressed in the FAQ section in the readme: https://github.com/sindresorhus/class-names#how-is-it-different-from-classnames

This package was extracted from my [`react-extras`](https://github.com/sindresorhus/react-extras) package.

**Comment by dextermb** [comment]
> It's already addressed in the FAQ section in the readme: https://github.com/sindresorhus/class-names#how-is-it-different-from-classnames
> 
> This package was extracted from my [`react-extras`](https://github.com/sindresorhus/react-extras) package.

Ah I missed this!
